sudo: required
services:
  - docker

before_install:
  - docker build -t joaquin767/docker-react -f Dockerfile.dev .

script:
  - docker run joaquin767/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "first-docker"
  env: "FirstDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-583561627847"
  bucket_path: "first-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"